/* PM1 Configuration  */

export const MYKAD_CODE = "01";
export const PASSPORT_CODE = "05";
export const GENDER_MALE_CODE = "M";
export const GENDER_FEMALE_CODE = "F";
export const MAE_INDICATOR_CONVENTIONAL = "0Y";
export const MAE_INDICATOR_ISLAMIC = "CC";
export const HIGH_RISK_CUSTOMER_CODE = "HR";
export const MEDIUM_RISK_CUSTOMER_CODE = "MR";
export const LOW_RISK_CUSTOMER_CODE = "LR";
export const PRE_QUAL_PRE_LOGIN_FLAG = "prelogin";
export const PREMIER_PRE_QUAL_POST_LOGIN_FLAG = "postlogin";
export const PREMIER_CLEAR_ALL = "PREMIER_CLEAR_ALL";
export const CARD_STP = "CARD_STP";
export const CARD_STP_VERIFY = "CARD_STP_VERIFY";
export const OTP_VERIFY = "TAC Application";
export const MYKAD_ID_TYPE = "MyKad";
export const PASSPORT_ID_TYPE = "Passport";
export const MAY_ONLY_CUST = "MAE1";
export const CHECK_08_SCREEN = "CHECK_08_SCREEN";

export const PM1_STP = "PM1_STP";
export const PM1_CASA_STP = "CASA_STP";
export const PM1_STP_VERIFY = "PM1_STP_VERIFY";

// User status
export const PM1_NTB_USER = "PM1_NTB_USER";
export const PM1_DRAFT_USER = "PM1_DRAFT_USER";
export const PM1_DRAFT_BRANCH_USER = "PM1_DRAFT_BRANCH_USER";
export const PM1_M2U_ONLY_USER = "PM1_M2U_ONLY_USER";
export const PM1_FULL_ETB_USER = "PM1_FULL_ETB_USER";
export const PM1_NON_KYC_USER = "PM1_NON_KYC_USER";
export const PM1_UNIDENTIFIED_USER = "PM1_UNIDENTIFIED_USER";
export const PM1_HIGH_RISK_USER = "PM1_HIGH_RISK_USER";
export const PM1_MAE_ONLY_USER = "PM1_MAE_ONLY_USER";
export const PM1_DEBIT_CARD_USER = "PM1_DEBIT_CARD_USER";
export const PM1_DEBIT_CARD_NTB_USER = "PM1_DEBIT_CARD_NTB_USER";
export const PM1_DEBIT_CARD_ACTIVATE_ACCOUNT_USER = "PM1_DEBIT_CARD_ACTIVATE_ACCOUNT_USER";
export const PM1_WITHOUT_M2U_USER = "PM1_WITHOUT_M2U_USER";

// common Custom exception codes
export const FUNDS_TRANSFER_EXCEPTION = 444;
export const M2U_SCREEN_SCORE_EXCEPTION = 4994;
export const CREATE_ACCOUNT_SCREEN_PARTY_TIMEOUT = 104;
export const CREATE_ACCOUNT_SCORE_PARTY_TIMEOUT = 105;
export const PREQUAL_PENDING_ACCOUNT_CREATION_STATUS = "3300";
export const CREATE_ACCOUNT_TIMEOUT_EXCEPTION = 5500;
export const CREATE_ACCOUNT_FAILURE_EXCEPTION = 103;
export const CREATE_ACCOUNT_SCREEN_CREATE_PARTY_TIMEOUT = "101";
export const CREATE_ACCOUNT_SCREEN_CREATE_ACCOUNT_FAILURE = "802";
export const CREATE_ACCOUNT_SCREEN_CREATE_PARTY_FAILURE = "801";
export const CREATE_ACCOUNT_SCREEN_CREATE_PARTY_FAILURE_MSG = "create party failure";

/* PMA Configuration */

export const CASA_STP = "CASA_STP";
export const CASA_STP_VERIFY = "CASA_STP_VERIFY";

// User status
export const PMA_NTB_USER = "PMA_NTB_USER";
export const PMA_DRAFT_USER = "PMA_DRAFT_USER";
export const PMA_DRAFT_BRANCH_USER = "PMA_DRAFT_BRANCH_USER";
export const PMA_M2U_ONLY_USER = "PMA_M2U_ONLY_USER";
export const PMA_FULL_ETB_USER = "PMA_FULL_ETB_USER";
export const PMA_NON_KYC_USER = "PMA_NON_KYC_USER";
export const PMA_UNIDENTIFIED_USER = "PMA_UNIDENTIFIED_USER";
export const PMA_HIGH_RISK_USER = "PMA_HIGH_RISK_USER";
export const PMA_MAE_ONLY_USER = "PMA_MAE_ONLY_USER";
export const PMA_DEBIT_CARD_USER = "PMA_DEBIT_CARD_USER";
export const PMA_DEBIT_CARD_NTB_USER = "PMA_DEBIT_CARD_NTB_USER";
export const PMA_DEBIT_CARD_ACTIVATE_ACCOUNT_USER = "PMA_DEBIT_CARD_ACTIVATE_ACCOUNT_USER";
export const PMA_WITHOUT_M2U_USER = "PMA_WITHOUT_M2U_USER";

// KAWANKU SAVINGS User status
export const KAWANKU_SAVINGS_NTB_USER = "KAWANKU_SAVINGS_NTB_USER";
export const KAWANKU_SAVINGS_DRAFT_USER = "KAWANKU_SAVINGS_DRAFT_USER";
export const KAWANKU_SAVINGS_DRAFT_BRANCH_USER = "KAWANKU_SAVINGS_DRAFT_BRANCH_USER";
export const KAWANKU_SAVINGS_M2U_ONLY_USER = "KAWANKU_SAVINGS_M2U_ONLY_USER";
export const KAWANKU_SAVINGS_FULL_ETB_USER = "KAWANKU_SAVINGS_FULL_ETB_USER";
export const KAWANKU_SAVINGS_NON_KYC_USER = "KAWANKU_SAVINGS_NON_KYC_USER";
export const KAWANKU_SAVINGS_UNIDENTIFIED_USER = "KAWANKU_SAVINGS_UNIDENTIFIED_USER";
export const KAWANKU_SAVINGS_HIGH_RISK_USER = "KAWANKU_SAVINGS_HIGH_RISK_USER";
export const KAWANKU_SAVINGS_MAE_ONLY_USER = "KAWANKU_SAVINGS_MAE_ONLY_USER";
export const KAWANKU_SAVINGS_DEBIT_CARD_USER = "KAWANKU_SAVINGS_DEBIT_CARD_USER";
export const KAWANKU_SAVINGS_DEBIT_CARD_NTB_USER = "KAWANKU_SAVINGS_DEBIT_CARD_NTB_USER";
export const KAWANKU_SAVINGS_DEBIT_CARD_ACTIVATE_ACCOUNT_USER =
    "KAWANKU_SAVINGS_DEBIT_CARD_ACTIVATE_ACCOUNT_USER";
export const KAWANKU_SAVINGS_WITHOUT_M2U_USER = "KAWANKU_SAVINGS_WITHOUT_M2U_USER";

// KAWANKU SAVINGS I User status
export const KAWANKU_SAVINGSI_NTB_USER = "KAWANKU_SAVINGSI_NTB_USER";
export const KAWANKU_SAVINGSI_DRAFT_USER = "KAWANKU_SAVINGSI_DRAFT_USER";
export const KAWANKU_SAVINGSI_DRAFT_BRANCH_USER = "KAWANKU_SAVINGSI_DRAFT_BRANCH_USER";
export const KAWANKU_SAVINGSI_M2U_ONLY_USER = "KAWANKU_SAVINGSI_M2U_ONLY_USER";
export const KAWANKU_SAVINGSI_FULL_ETB_USER = "KAWANKU_SAVINGSI_FULL_ETB_USER";
export const KAWANKU_SAVINGSI_NON_KYC_USER = "KAWANKU_SAVINGSI_NON_KYC_USER";
export const KAWANKU_SAVINGSI_UNIDENTIFIED_USER = "KAWANKU_SAVINGSI_UNIDENTIFIED_USER";
export const KAWANKU_SAVINGSI_HIGH_RISK_USER = "KAWANKU_SAVINGSI_HIGH_RISK_USER";
export const KAWANKU_SAVINGSI_MAE_ONLY_USER = "KAWANKU_SAVINGSI_MAE_ONLY_USER";
export const KAWANKU_SAVINGSI_DEBIT_CARD_USER = "KAWANKU_SAVINGSI_DEBIT_CARD_USER";
export const KAWANKU_SAVINGSI_DEBIT_CARD_NTB_USER = "KAWANKU_SAVINGSI_DEBIT_CARD_NTB_USER";
export const KAWANKU_SAVINGSI_DEBIT_CARD_ACTIVATE_ACCOUNT_USER =
    "KAWANKU_SAVINGSI_DEBIT_CARD_ACTIVATE_ACCOUNT_USER";
export const KAWANKU_SAVINGSI_WITHOUT_M2U_USER = "KAWANKU_SAVINGSI_WITHOUT_M2U_USER";
